// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LoadPlansController from "./plans/load_table.js"
import LoadCustomersController from "./customers/load_table.js"
import LoadSubscriptionsController from "./subscriptions/load_table.js"
import LoadTrainingsController from "./trainings/load_table.js"
import DestroySubscription from "./subscriptions/destroy.js"
import DestroyCustomer from "./customers/destroy.js"
import DestroyTraining from "./trainings/destroy.js"
application.register("loadPlans", LoadPlansController)
application.register("loadCustomers", LoadCustomersController)
application.register("loadSubscriptions", LoadSubscriptionsController)
application.register("loadTrainings", LoadTrainingsController)
application.register("destroySubscription", DestroySubscription)
application.register("destroyCustomer", DestroyCustomer)
application.register("destroyTraining", DestroyTraining)